<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginaFormSubmission extends BaseaFormSubmission
{
	
	public function getFieldSubmissionsForLayout($layout_id)
	{
		$aFieldSubmissions = array();
		foreach($this->aFormFieldSubmissions as $aFieldSubmission)
		{
			if($aFieldSubmission['layout_id'] == $layout_id)
			{
				$aFieldSubmissions[] = $aFieldSubmission;
			}
		}
		return $aFieldSubmissions;
	}
}