<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginaFormLayout extends BaseaFormLayout
{ 
  protected $form;
  
  protected static $types = array(
    'input' => 'Text Field',
    'textarea' => 'Text Area', 
    'select' => 'Select Menu', 
    'select_radio' => 'Radio Select', 
    'select_checkbox' => 'Check Box', 
    // 'confirmation' => 'Confirmation Box', 
    // 'email' => 'Email Field', 
    'address' => 'Address Fields',
  );
  
  public static function getTypes()
  {
    return self::$types;
  }
   
  public function getFormClass()
  {
    return 'aForm'.sfInflector::camelize($this->getType());
  }
    
  public function getFormOptions()
  {
    $options = array(
      'slug' => $this->getSlug(), 
      'label' => $this->getLabel(),
      'required' => $this->getRequired(),
    );
    
    if ($this->usesOptions())
    {
      $options['choices'] = array();
      foreach ($this->aFormLayoutOptions as $choice)
      {
        $options['choices'][(string)$choice->getValue()] = $choice->getName();
      }
    }
    
    return $options;
  }
  
  public function usesOptions()
  {
    if (in_array($this->getType(), array('select', 'select_radio', 'select_checkbox')))
    {
      return true;
    }
    
    return false;
  }
  
  public function getForm($defaults = null, $options = array())
  {

    $class = $this->getFormClass();
    $this->form = new $class($defaults, array_merge($options, $this->getFormOptions()));
    
    return $this->form;
  }
  
  public function getOptionsForm()
  {
    $form = new aFormLayoutOptionsForm(null, array('a_form_layout' => $this));
    
    return $form;
  }
  
  public function preSave($event)
  {
    if ($this->isNew())
    {
      $this->setRank($this->aForm->getMaxRank() + 1);
      foreach($this->getForm()->getObjects() as $name => $object)
      {
        $field = new aFormField();
        $field->setName($name);
        $this->aFormFields[] = $field;
      }
    }
  }
  
  public function preDelete($event)
  {
    foreach ($this->getpkForm()->getpkFormFields() as $field)
    {
      if ($field->getRank() > $this->getRank())
      {
        $field->setRank($field->getRank() - 1);
        $field->save();
      }
    }
  }
}