<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginaFormField extends BaseaFormField
{
  protected static $types = array(
    'input' => 'Text Field',
    'textarea' => 'Text Area', 
    'select' => 'Select Menu', 
    'select_radio' => 'Radio Select', 
    'select_checkbox' => 'Check Box', 
    // 'confirmation' => 'Confirmation Box', 
    // 'email' => 'Email Field', 
    'address' => 'Address Fields',
  );
  
  public static function getTypes()
  {
    return self::$types;
  }
  
  public function getFormClass()
  {
    return 'aForm'.sfInflector::camelize($this->getType());
  }
    
  public function getFormOptions()
  {
    $options = array(
      'slug' => $this->getSlug(), 
      'label' => $this->getLabel(),
      'required' => $this->getRequired(), 
    );
    
    if ($this->usesOptions())
    {
      $options['choices'] = array();
      foreach ($this->getpkFormFieldOptions() as $choice)
      {
        $options['choices'][(string)$choice->getName()] = $choice->getName();
      }
    }
    
    return $options;
  }
  
  public function usesOptions()
  {
    if (in_array($this->getType(), array('select', 'select_radio', 'select_checkbox')))
    {
      return true;
    }
    
    return false;
  }
  
  public function getForm($defaults = null, $options = array())
  {
    $class = $this->getFormClass();
    $form = new $class($defaults, array_merge($options, $this->getFormOptions()));
    
    return $form;
  }
  
  public function getOptionsForm()
  {
    $form = new aFormFieldOptionsForm(null, array('a_form_field' => $this));
    
    return $form;
  }
  
  public function preSave($event)
  {
    if ($this->isNew())
    {
      $a_form = Doctrine::getTable('aForm')->find($this->getFormId());

      $this->setRank($a_form->getMaxRank() + 1);
    }
  }
  
  public function preDelete($event)
  {
    foreach ($this->getpkForm()->getpkFormFields() as $field)
    {
      if ($field->getRank() > $this->getRank())
      {
        $field->setRank($field->getRank() - 1);
        $field->save();
      }
    }
  }
}