<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginaFormSubmission extends BaseaFormSubmission
{
	
	public function getFieldSubmissionsForFieldset($fieldset_id)
	{
		$aFieldSubmissions = array();
		foreach($this->aFormFieldSubmissions as $aFieldSubmission)
		{
			if($aFieldSubmission['fieldset_id'] == $fieldset_id)
			{
				$aFieldSubmissions[] = $aFieldSubmission;
			}
		}
		return $aFieldSubmissions;
	}
}