<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginaForm extends BaseaForm
{
  protected $fieldCount;
  
  public function getfieldCount()
  {
    $count = 0;
		foreach($this->aFormLayouts as $aFormLayout)
		  $count = count($aFormLayout) + $count;
	  return $count;
  }
  
  public function buildForm()
  {
    return new aFormBuilder(null, array('a_form' => $this));
  }
  
  public function fetchFieldByRank($rank = 1)
  {
    $q = Doctrine::getTable('aFormLayout')
      ->createQuery('ff')
      ->innerJoin('ff.aForm f WITH f.id = ?', $this->getId())
      ->where('ff.rank = ?', $rank);
    
    return $q->fetchOne();
  }
  
  public function getAllFieldsByRank()
  {
    $q = Doctrine::getTable('aFormLayout')
      ->createQuery('ff')
      ->innerJoin('ff.aForm f WITH f.id = ?', $this->getId())
      ->orderBy('ff.rank');
    
    return $q->execute();
  }
  
  public function getMaxRank()
  {
    return $this->getTable()->getMaxRank($this->getId());
  }
}