<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaFormTable extends Doctrine_Table
{

  public function getMaxRank($id)
  {
    $q = Doctrine_Query::create()
      ->select('max(ff.rank) as max')
      ->from('aFormLayout ff')
      ->innerJoin('ff.aForm f WITH f.id = ?', $id);

    $result = $q->fetchOne();
    return $result['max'];
  }
}