<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginaForm extends BaseaForm
{
  public function buildForm()
  {
    return new aFormBuilder(null, array('a_form' => $this));
  }
  
  public function fetchFieldByRank($rank = 1)
  {
    $q = Doctrine::getTable('aFormLayout')
      ->createQuery('ff')
      ->innerJoin('ff.aForm f WITH f.id = ?', $this->getId())
      ->where('ff.rank = ?', $rank);
    
    return $q->fetchOne();
  }
  
  public function getAllFieldsByRank()
  {
    $q = Doctrine::getTable('aFormLayout')
      ->createQuery('ff')
      ->innerJoin('ff.aForm f WITH f.id = ?', $this->getId())
      ->orderBy('ff.rank');
    
    return $q->execute();
  }
  
  public function getMaxRank()
  {
    $q = Doctrine_Query::create()
      ->select('max(ff.rank) as max')
      ->from('aFormLayout ff')
      ->innerJoin('ff.aForm f WITH f.id = ?', $this->getId());

    $result = $q->fetchOne();
        
    return $result['max'];
  }
}