<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaFormFieldTable extends Doctrine_Table
{
  public function doSort($order = array())
  {
    $fields = array();
    foreach ($order as $rank => $id) 
    {
      $field = $this->find($id);
      
      if ($field->getRank() != $rank)
      {
        $field->setRank($rank);
        $field->save();
      }
      
      $fields[] = $field;
    }
    
    return $fields;
  }
}