<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaFormLayoutTable extends Doctrine_Table
{
  protected static $types = array(
    'input' => 'Text Field',
    'textarea' => 'Text Area', 
    'select' => 'Select Menu', 
    'select_radio' => 'Radio Select', 
    'select_checkbox' => 'Check Box', 
    // 'confirmation' => 'Confirmation Box', 
    // 'email' => 'Email Field', 
    'address' => 'Address Fields',
  );
  
  public static function getTypes()
  {
    return self::$types;
  }

  //TODO: No need to sort every layout when one is moved can change to an update query
  public function doSort($order = array())
  {
    $fields = array();
    foreach ($order as $rank => $id) 
    {
      $field = $this->find($id);
      
      if ($field->getRank() != $rank)
      {
        $field->setRank($rank);
        $field->save();
      }
      
      $fields[] = $field;
    }
    
    return $fields;
  }
}