<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginaFormField extends BaseaFormField
{  
  public function getFormClass()
  {
    return 'aForm'.sfInflector::camelize($this->getType());
  }
    
  public function getFormOptions()
  {
    $options = array(
      'slug' => $this->getSlug(), 
      'label' => $this->getLabel(),
      'required' => $this->getRequired(),
    );
    
    if ($this->usesOptions())
    {
      $options['choices'] = array();
      foreach ($this->aFormFieldOptions as $choice)
      {
        $options['choices'][(string)$choice->getValue()] = $choice->getName();
      }
    }
    
    return $options;
  }
  
  public function usesOptions()
  {
    if (in_array($this->getType(), array('select', 'select_radio', 'select_checkbox')))
    {
      return true;
    }
    
    return false;
  }
  
  public function getForm($defaults = null, $options = array())
  {
    $class = $this->getFormClass();
    $form = new $class($defaults, array_merge($options, $this->getFormOptions()));
    
    return $form;
  }
  
  public function getOptionsForm()
  {
    $form = new aFormFieldOptionsForm(null, array('a_form_field' => $this));
    
    return $form;
  }
  
  public function preSave($event)
  {
    if ($this->isNew())
    {
      $this->setRank($this->aForm->getMaxRank() + 1);
    }
  }
  
  public function preDelete($event)
  {
    foreach ($this->getpkForm()->getpkFormFields() as $field)
    {
      if ($field->getRank() > $this->getRank())
      {
        $field->setRank($field->getRank() - 1);
        $field->save();
      }
    }
  }
}