<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2010/02/16 17:35:01
return array(

  // apostropheFormBuilderPlugin_module_libs
  'aForm/baseaformactions' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/modules/aForm/lib/BaseaFormActions.class.php',
  'aFormSlot/baseaformslotactions' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/modules/aFormSlot/lib/BaseaFormSlotActions.class.php',
  'aFormSlot/baseaformslotcomponents' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/modules/aFormSlot/lib/BaseaFormSlotComponents.class.php',
  'aFormSubmission/baseaformsubmissionactions' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/modules/aFormSubmission/lib/BaseaFormSubmissionActions.class.php',
  'aFormSubmission/baseaformsubmissioncomponents' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/modules/aFormSubmission/lib/BaseaFormSubmissionComponents.class.php',
  'aFormSubmissionAdmin/aformsubmissionadmingeneratorconfiguration' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/modules/aFormSubmissionAdmin/lib/aFormSubmissionAdminGeneratorConfiguration.class.php',
  'aFormSubmissionAdmin/aformsubmissionadmingeneratorhelper' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/modules/aFormSubmissionAdmin/lib/aFormSubmissionAdminGeneratorHelper.class.php',
  'aFormSubmissionAdmin/baseaformsubmissionadminactions' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/modules/aFormSubmissionAdmin/lib/BaseaFormSubmissionAdminActions.class.php',

  // apostropheFormBuilderPlugin_lib
  'aformbuilderfilter' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/filter/aFormBuilderFilter.class.php',
  'pluginaformfieldformfilter' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/filter/doctrine/PluginaFormFieldFormFilter.class.php',
  'pluginaformfieldsubmissionformfilter' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/filter/doctrine/PluginaFormFieldSubmissionFormFilter.class.php',
  'pluginaformformfilter' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/filter/doctrine/PluginaFormFormFilter.class.php',
  'pluginaformlayoutformfilter' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/filter/doctrine/PluginaFormLayoutFormFilter.class.php',
  'pluginaformlayoutoptionformfilter' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/filter/doctrine/PluginaFormLayoutOptionFormFilter.class.php',
  'pluginaformslotformfilter' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/filter/doctrine/PluginaFormSlotFormFilter.class.php',
  'pluginaformsubmissionformfilter' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/filter/doctrine/PluginaFormSubmissionFormFilter.class.php',
  'aformbuilder' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/aFormBuilder.class.php',
  'aformembeddable' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/aFormEmbeddable.class.php',
  'aformlayoutoptionsform' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/aFormFieldOptionsForm.class.php',
  'pluginaformfieldform' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/doctrine/PluginaFormFieldForm.class.php',
  'pluginaformfieldsubmissionform' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/doctrine/PluginaFormFieldSubmissionForm.class.php',
  'pluginaformform' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/doctrine/PluginaFormForm.class.php',
  'pluginaformlayoutform' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/doctrine/PluginaFormLayoutForm.class.php',
  'pluginaformlayoutoptionform' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/doctrine/PluginaFormLayoutOptionForm.class.php',
  'pluginaformslotform' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/doctrine/PluginaFormSlotForm.class.php',
  'pluginaformsubmissionform' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/doctrine/PluginaFormSubmissionForm.class.php',
  'aformaddress' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/layout/aFormAddress.class.php',
  'aforminput' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/layout/aFormInput.class.php',
  'aformselect' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/layout/aFormSelect.class.php',
  'aformselectcheckbox' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/layout/aFormSelectCheckbox.class.php',
  'aformselectradio' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/layout/aFormSelectRadio.class.php',
  'aformtextarea' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/form/layout/aFormTextarea.class.php',
  'pluginaform' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/model/doctrine/PluginaForm.class.php',
  'pluginaformfield' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/model/doctrine/PluginaFormField.class.php',
  'pluginaformfieldsubmission' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/model/doctrine/PluginaFormFieldSubmission.class.php',
  'pluginaformfieldsubmissiontable' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/model/doctrine/PluginaFormFieldSubmissionTable.class.php',
  'pluginaformfieldtable' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/model/doctrine/PluginaFormFieldTable.class.php',
  'pluginaformlayout' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/model/doctrine/PluginaFormLayout.class.php',
  'pluginaformlayoutoption' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/model/doctrine/PluginaFormLayoutOption.class.php',
  'pluginaformlayoutoptiontable' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/model/doctrine/PluginaFormLayoutOptionTable.class.php',
  'pluginaformlayouttable' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/model/doctrine/PluginaFormLayoutTable.class.php',
  'pluginaformslot' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/model/doctrine/PluginaFormSlot.class.php',
  'pluginaformslottable' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/model/doctrine/PluginaFormSlotTable.class.php',
  'pluginaformsubmission' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/model/doctrine/PluginaFormSubmission.class.php',
  'pluginaformsubmissiontable' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/model/doctrine/PluginaFormSubmissionTable.class.php',
  'pluginaformtable' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/model/doctrine/PluginaFormTable.class.php',
  'aformbrowser' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/test/aFormBrowser.class.php',
  'aformtestfunctional' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/test/aFormTestFunctional.class.php',
  'aformtesttoolkit' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/lib/test/aFormTestToolkit.class.php',

  // project
  'baseform' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/test/fixtures/project/lib/form/BaseForm.class.php',

  // project_model

  // application
  'myuser' => '/Users/alex/Sites/waytohealth/plugins/apostropheFormBuilderPlugin/test/fixtures/project/apps/frontend/lib/myUser.class.php',

  // modules
);
