<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/02/22 14:37:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=waytohealth',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
